noinst_PROGRAMS = unittest

unittest_SOURCES = \
	unittest_main.cpp \
	$(NULL)

unittest_LDFLAGS = \
	$(AM_LDFLAGS) \
	-pthread \
	$(NULL)

unittest_LDADD = \
	libyami_capi.la \
	$(top_srcdir)/gtestsrc/libgtest.la \
	$(NULL)

unittest_CPPFLAGS = \
	$(AM_CPPFLAGS) \
	-I$(top_srcdir)/interface \
	-I$(top_srcdir)/gtestsrc/gtest/include \
	$(NULL)

unittest_CXXFLAGS = \
	$(AM_CXXFLAGS) \
	$(NULL)

check-local: unittest
	$(builddir)/unittest

